INSERT INTO flights (origin, destination, duration) VALUES ('New York', 'London', 415);
INSERT INTO flights (origin, destination, duration) VALUES ('Shanghai', 'Paris', 760);
INSERT INTO flights (origin, destination, duration) VALUES ('Istanbul', 'Tokyo', 700);
INSERT INTO flights (origin, destination, duration) VALUES ('New York', 'Paris', 435);
INSERT INTO flights (origin, destination, duration) VALUES ('Moscow', 'Paris', 245);
INSERT INTO flights (origin, destination, duration) VALUES ('Lima', 'New York', 455);
INSERT INTO flights (origin, destination, duration) VALUES ('Paris', 'New York', 540);
INSERT INTO flights (origin, destination, duration) VALUES ('Tokyo', 'Shanghai', 185);
INSERT INTO flights (origin, destination, duration) VALUES ('Seoul', 'Mexico City', 825);
INSERT INTO flights (origin, destination, duration) VALUES ('Mexico City', 'Lima', 350);
INSERT INTO flights (origin, destination, duration) VALUES ('Honk Kong', 'Shanghai', 130);