SELECT * FROM flights;
SELECT origin, destination FROM flights;
SELECT destination, duration FROM flights;
SELECT * FROM flights WHERE id = 3;
SELECT * FROM flights WHERE id = 3 OR id = 4;
SELECT * FROM flights WHERE origin = 'Shanghai';
SELECT * FROM flights WHERE destination = 'Paris';
SELECT * FROM flights WHERE duration > 500;
SELECT * FROM flights WHERE destination = 'Paris' AND duration > 500;
SELECT * FROM flights WHERE destination = 'Paris' OR duration > 500;
SELECT AVG(duration) FROM flights;
SELECT AVG(duration) FROM flights WHERE origin = 'New York';
SELECT COUNT(*) FROM flights;
SELECT COUNT(*) FROM flights WHERE origin = 'New York';
SELECT MIN(duration) FROM flights;
SELECT * FROM flights WHERE duration = 245;
SELECT MAX(duration) FROM flights;
SELECT * FROM flights WHERE duration = 760;
SELECT * FROM flights WHERE origin IN ('New York', 'Lima');
SELECT * FROM flights WHERE origin LIKE '%a%';
SELECT * FROM flights WHERE destination LIKE '%o%';
SELECT * FROM flights ORDER BY id ASC;
